// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IceCream is an autogenerated mock type for the IceCream type
type IceCream struct {
	mock.Mock
}

// Price provides a mock function with given fields:
func (_m *IceCream) Price() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewIceCream interface {
	mock.TestingT
	Cleanup(func())
}

// NewIceCream creates a new instance of IceCream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIceCream(t mockConstructorTestingTNewIceCream) *IceCream {
	mock := &IceCream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
